// Root.tsx
import { Composition } from "remotion";
import { SlideComposition } from "./SlideComposition";
import { FullPresentation } from "./FullPresentation";
import corporateDark from "./templates/corporate-dark";
import { natureLight } from "./templates/nature-light";
import { samplePresentation } from "./sample-presentation";
import { AvatarMap, computeSlideDurationFrames } from "./components/presentation/GenericSlideRenderer";
import "./index.css";

// Mock avatar data for preview — keyed by narrated element id.
// In a real app, these are generated by an ML pipeline after TTS audio is produced.
//
// Narrated elements in sample-presentation.ts:
//   el6  — s2 body-text  "A mangrove ecosystem is a coastal wetland…"
//   el23 — s5 bullet-list "Mangrove forests are among the most biodiverse…"
//   el26 — s6 headline    "Importance to Coastal Protection"
//   el38 — s8 headline    "Conservation Efforts"
//   el49 — s10 headline   "Conclusion"
const sampleAvatarMap: AvatarMap = {
  el6:  { src: "https://s3.renderplatform.com/user-assets/preview/generated_video/d8634ece-ede9-4bfd-beee-74e2ddc2b93c.mp4", durationInSeconds: 13.5 },
  el23: { src: "https://s3.renderplatform.com/user-assets/preview/generated_video/d8634ece-ede9-4bfd-beee-74e2ddc2b93d.mp4", durationInSeconds: 11.5 },
  el26: { src: "/assets/avatars/speaker1.mp4", durationInSeconds: 8 },
  el38: { src: "/assets/avatars/speaker1.mp4", durationInSeconds: 8 },
  el49: { src: "/assets/avatars/speaker1.mp4", durationInSeconds: 7 },
};

export const RemotionRoot: React.FC = () => {
  const fps = 30;

  // Calculate duration for the full presentation
  const fullDurationInFrames = samplePresentation.slides.reduce((total, slide) => {
    return total + computeSlideDurationFrames(slide, fps, sampleAvatarMap);
  }, 0);

  return (
    <>
      <Composition
        id="NatureLight-FullPresentation"
        component={FullPresentation as any}
        durationInFrames={fullDurationInFrames}
        fps={fps}
        width={1920}
        height={1080}
        schema={undefined} // FullPresentation handles its own props via defaultProps for now
        defaultProps={{
          presentation: samplePresentation,
          template: natureLight,
          avatarMap: sampleAvatarMap,
        }}
      />

      {/* Individual slide previews */}
      {samplePresentation.slides.map((slide) => (
        <Composition
          key={slide.id}
          id={`NatureLight-${slide.id}`}
          component={SlideComposition as any}
          durationInFrames={computeSlideDurationFrames(slide, fps, sampleAvatarMap)}
          fps={fps}
          width={1920}
          height={1080}
          defaultProps={{
            slide,
            template: natureLight,
            avatarMap: sampleAvatarMap,
          }}
        />
      ))}

      {/* Corporate Dark (Legacy Preview) */}
      <Composition
        id="CorporateDark-FullPresentation"
        component={FullPresentation as any}
        durationInFrames={fullDurationInFrames}
        fps={fps}
        width={1920}
        height={1080}
        defaultProps={{
          presentation: { ...samplePresentation, templateId: "corporate-dark" },
          template: corporateDark,
          avatarMap: sampleAvatarMap,
        }}
      />
    </>
  );
};
