// Root.tsx
import { Composition } from "remotion";
import { SlideComposition } from "./SlideComposition";
import { FullPresentation } from "./FullPresentation";
import corporateDark from "./templates/corporate-dark";
import { natureLight } from "./templates/nature-light";
import { samplePresentation } from "./sample-presentation";
import { AvatarMap, computeSlideDurationFrames } from "./components/presentation/GenericSlideRenderer";
import "./index.css";

// Mock avatar data for preview.
// In a real app, these are generated by an ML pipeline.
const sampleAvatarMap: AvatarMap = {
  // Slide 1
  el1: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 2
  el5: { src: "/avatars/speaker1.mp4", durationInSeconds: 9 },
  // Slide 3
  el14: { src: "/avatars/speaker1.mp4", durationInSeconds: 9 }, // Was el14 on slide 4, now slide 3 panel headline
  // Slide 4 (Structure)
  el18: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 5 (Biodiversity)
  el22: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 6 (Coastal)
  el26: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 7 (Threats)
  el32: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 8 (Conservation)
  el38: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 9 (Future)
  el45: { src: "/avatars/speaker1.mp4", durationInSeconds: 8 },
  // Slide 10 (Conclusion)
  el49: { src: "/avatars/speaker1.mp4", durationInSeconds: 7 },
};

export const RemotionRoot: React.FC = () => {
  const fps = 30;

  // Calculate duration for the full presentation
  const fullDurationInFrames = samplePresentation.slides.reduce((total, slide) => {
    return total + computeSlideDurationFrames(slide, fps, sampleAvatarMap);
  }, 0);

  return (
    <>
      <Composition
        id="NatureLight-FullPresentation"
        component={FullPresentation as any}
        durationInFrames={fullDurationInFrames}
        fps={fps}
        width={1920}
        height={1080}
        schema={undefined} // FullPresentation handles its own props via defaultProps for now
        defaultProps={{
          presentation: samplePresentation,
          template: natureLight,
          avatarMap: sampleAvatarMap,
        }}
      />

      {/* Individual slide previews */}
      {samplePresentation.slides.map((slide) => (
        <Composition
          key={slide.id}
          id={`NatureLight-${slide.id}`}
          component={SlideComposition as any}
          durationInFrames={computeSlideDurationFrames(slide, fps, sampleAvatarMap)}
          fps={fps}
          width={1920}
          height={1080}
          defaultProps={{
            slide,
            template: natureLight,
            avatarMap: sampleAvatarMap,
          }}
        />
      ))}

      {/* Corporate Dark (Legacy Preview) */}
      <Composition
        id="CorporateDark-FullPresentation"
        component={FullPresentation as any}
        durationInFrames={fullDurationInFrames}
        fps={fps}
        width={1920}
        height={1080}
        defaultProps={{
          presentation: { ...samplePresentation, templateId: "corporate-dark" },
          template: corporateDark,
          avatarMap: sampleAvatarMap,
        }}
      />
    </>
  );
};
